"""Synthetic Lake root generation."""

from __future__ import annotations

import json

from .specs import EnvironmentSpec

ROOT_PACKAGE = "lean_runtime_environment"
ROOT_MODULE = "LeanRuntimeEnvironment"


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate_lakefile(spec: EnvironmentSpec) -> str:
    lines = [
        f"name = {_quote(ROOT_PACKAGE)}",
        'version = "0.0.0"',
        'defaultTargets = ["LeanRuntimeEnvironment"]',
        "",
    ]
    for package in sorted(spec.packages, key=lambda item: item.name):
        lines.extend(
            [
                "[[require]]",
                f"name = {_quote(package.name)}",
                f"git = {_quote(package.url)}",
                f"rev = {_quote(package.rev.lower())}",
            ]
        )
        if package.subdir:
            lines.append(f"subDir = {_quote(package.subdir)}")
        lines.append("")
    lines.extend(["[[lean_lib]]", f"name = {_quote(ROOT_MODULE)}", ""])
    return "\n".join(lines)


def generate_root_module(spec: EnvironmentSpec) -> str:
    imports = [f"import {package.module}" for package in spec.packages]
    return "\n".join([*imports, "", "/- Generated by Lean Runtime. -/", ""])
